### ISSUE TITLE
Fatal error, room script not working: BROWSER LOG ERROR 

### ISSUE THREAD

**Issue by DarXe** [morko/haxroomie#123]
how to avoid, repair web browser error?
![Screen Shot 08-13-23 at 12 25 AM 001](https://github.com/morko/haxroomie/assets/51196717/959e6968-54d0-4d57-be9e-db40fedcb4ad)

**Comment by saviola777** [comment]
The error is pretty clear, there is a syntax error in your script. Use a tool like [this](https://jsvalidator.com/) to check your syntax, and keep in mind that haxroomie bundles Chromium 78, so any ES features included after that are not available (for example optional chaining).

**Comment by DarXe** [comment]
> The error is pretty clear, there is a syntax error in your script. Use a tool like [this](https://jsvalidator.com/) to check your syntax, and keep in mind that haxroomie bundles Chromium 78, so any ES features included after that are not available (for example optional chaining).

thanks for reply!
