### ISSUE TITLE
Wrong link to default config file

### ISSUE THREAD

**Issue by saviola777** [morko/haxroomie#13]
The link to the default config gives a 404 error. You could also link to

https://github.com/saviola777/haxball-headless-manager/blob/master/config/default.js

at this point, since my default config is "haxroomie-compatible" I believe.

**Comment by morko** [comment]
Fixed in 64364a26cec0f6cca21eb0beb0d4044fd3dd56c0. Changed the file so much that I can not link your file.

**Comment by saviola777** [comment]
I see, how about using some deep merging of objects, like [this](https://stackoverflow.com/questions/27936772/how-to-deep-merge-instead-of-shallow-merge/34749873#34749873) or [lodash.merge](https://www.npmjs.com/package/lodash.merge) or [jQuery.extend](https://api.jquery.com/jquery.extend/)?
Would be cleaner, and HHM pulls in jQuery anyway (originally for DOM manipulation, now only for these QoL things :D Maybe I should reconsider that).
