### ISSUE TITLE
Do not restart room if only pluginConfig is changed when reloading

### ISSUE THREAD

**Issue by morko** [morko/haxroomie#27]
In the CLI if user does `reload` and the only property in the config changed is the `pluginConfig`, it will still restart the room although it is not needed.

**Comment by morko** [comment]
Reloading the `repositories` and `plugins` should work same way. So if only `pluginConfig`, `repositories` or `plugins` are changed there is no need to restart the room.

**Comment by morko** [comment]
Hot loading `plugins` does not work and can not work if HHM does not support unloading the plugin that is being hot loaded.

**Comment by saviola777** [comment]
I've been wondering about unloading plugins. When just looking at event handlers, it's simple: Remove the handlers from the HHM, then get rid of the plugin, done. But what about things like custom intervals (which are not officially supported, but some people will probably still use them), or plugins interacting with each other? Unloading a plugin that is a dependency of another plugin leaves the system in an invalid state, any events being processed in the time between unloading and loading the new version will likely lead to (hard to reproduce) errors.

It's not impossible to implement, but it's non-trivial and the question is: is it worth it?

**Comment by morko** [comment]
Yeah this feature is not necessary, but it could work same way as disabling plugins so that it would fail to unload the plugin when other plugin depends on it. And for the intervals there could be an event handler like `onPluginUnload` that the plugin could use to clear any intervals etc.

I would prefer this handler approach also in case of disabling/enabling the plugins because your cron plugin might get the job done it requires to learn a new API to accomplish the job and more work for you to upkeep it.

Anywayyys I have to leave this issue open until I remove the hot loading of plugins from my development branch (don't know why i thought it would work). :)

**Comment by morko** [comment]
Wait for https://github.com/saviola777/haxball-headless-manager/issues/21 to get solved to reload the repositories properly.

**Comment by morko** [comment]
Do not support hot loading `repositories` for now.
