### ISSUE TITLE
Support noPlayer option

### ISSUE THREAD

**Issue by saviola777** [morko/haxroomie#63]
Currently it is not possible to use the new `noPlayer` option in the haxroomie config.

The reason for this is that the options are merged individually in `src/hhm/config.js`.

It would be nice if this would be more flexible so that new options in the future would be supported without manually adding them in the haxroomie code.

**Comment by morko** [comment]
Hopefully this will work. Could not test atm. due to bad internet. Will test later.

**Comment by saviola777** [comment]
Yes, it works
