### ISSUE TITLE
HHM plugin.isEnabled is a function

### ISSUE THREAD

**Issue by saviola777** [morko/haxroomie#65]
I saw you are using `isEnabled` as a property in several places, when it is a function.

**Comment by morko** [comment]
You might be seeing the usage of serialized version of the plugin since i have a PluginData object that is serialized in the browser and then sent to the main "context" because cant send functions from there. Ill double check for those to make sure when I have time.

**Comment by saviola777** [comment]
Oops, sorry, you are right, I'll close this.
