### ISSUE TITLE
HHM 1.0.0 compatibility

### ISSUE THREAD

**Issue by saviola777** [morko/haxroomie#67]
Some deprecated functions were removed in HHM 1.0.0, here's the list plus the new names:

- `hasPluginByName` -> `hasPlugin`
- `hasPluginById` -> `hasPlugin`
- `getPluginByName` -> `getPlugin`
- `getPluginById` -> `getPlugin`
- `getDependentPluginsById` -> `getDependentPlugins`
- `enablePluginById` -> `enablePlugin`
- `disablePluginById` -> `disablePlugin`
- `addPluginByCode` -> `addPlugin( { pluginCode })`
- `addPluginByName` -> `addPlugin( { pluginName })`

If you want I can create a PR, just let me know which branch I should work with.

**Comment by morko** [comment]
The master branch was clean of these methods already.
