### ISSUE TITLE
Account for `null` values in `players` command

### ISSUE THREAD

**Issue by briantingtc** [morko/haxroomie#84]
Just ran into an exception while using the `players` command:
<img width="948" alt="Screen Shot 2020-05-03 at 5 18 17 PM" src="https://user-images.githubusercontent.com/13473157/80930215-e23c3a80-8d66-11ea-9c2a-5262e8a49e50.png">

https://github.com/morko/haxroomie/blob/164019778c48ce7978b91be7d791a80545e2aecd/packages/haxroomie-cli/src/command/handlers/BaseCommands.js#L233

Looks like we're not accounting for null values here and it worked when I changed it to this locally:  `playerList = playerList.filter(p => (p && p.id !== 0));` 

The quirk is that the headless host is represented by `null` when this is called:
https://github.com/morko/haxroomie/blob/164019778c48ce7978b91be7d791a80545e2aecd/packages/haxroomie-cli/src/command/handlers/BaseCommands.js#L232

What's returned from the function:
```javascript
playerList [
  null, // <--- I'm guessing this is supposed to be the headlesshost
  { name: 'me',
    team: 0,
    id: 1,
    admin: false,
    position: null,
    ...
  } ]
```

Thanks for all your hard work @morko, haxroomie is a joy to use

**Comment by briantingtc** [comment]
Looks like this is only if the room config option `noPlayers` is set to `true`:

`let playerList = await this.room.callRoom('getPlayerList');` returns this: 
`[ { name: 'host', team: 0, id: 0, admin: true, position: null } ]`

**Comment by briantingtc** [comment]
This is still happening intermittently even with `noPlayers` set to `false` -- I'm not sure of the source but this would be a trivial fix to merge in.

**Comment by morko** [comment]
Hey. Thanks for reporting this! Sorry I have been busy with stuff lately, but I will try to give some time for haxroomie this weekend and also fix this bug.

If you have time can you tell if you have the `sav/players` plugin enabled on the host that this is happening?

**Comment by saviola777** [comment]
Yeah, this looks like a `sav/players` bug, but one that I thought I fixed long ago. Which version of haxroomie / HHM / `sav/players` are you using?

**Comment by morko** [comment]
Could not replicate the situation where the playerlist would contain a null value in the latest version of haxroomie but I will add a check for it to be sure.
