### ISSUE TITLE
ReferenceError: HBInit is not defined

### ISSUE THREAD

**Issue by luangs7** [morko/haxroomie#98]
Hey guys, I am using Google Cloud to learn how to open a headless room.

But I am getting some errors here.

With `haxroomie-cli -c bot.js` i am getting:
`ReferenceError: HBInit is not defined
    at Object.<anonymous> (/home/luan263/bot/bot.js:1:14)`

Here is my bot.js file:
		

> var room = HBInit({
> 			autoStart: true,
> 			roomName: "Stadium Futsal x4",
> 			playerName: "ᴮᴼᵀ",
> 			maxPlayers: 16,
> 			public: true,
> 			noPlayer: false
> 		});
> 		room.setDefaultStadium("Big");
> 		room.setScoreLimit(3);
> 		room.setTimeLimit(4);
> 		room.setTeamsLock(true)

What I am doing wrong here?

**Comment by saviola777** [comment]
The `-c` parameter expects a haxroomie config file, not a room script. See the [own-roomscript.js](https://github.com/morko/haxroomie/tree/master/packages/haxroomie-cli/examples/configs/own-roomscript.js) for an example how you can load your room script.

**Comment by luangs7** [comment]
> The `-c` parameter expects a haxroomie config file, not a room script. See the [own-roomscript.js](https://github.com/morko/haxroomie/tree/master/packages/haxroomie-cli/examples/configs/own-roomscript.js) for an example how you can load your room script.

I got it, thanks.
